### ISSUE TITLE
公众号/企鹅群建议可以配置

### ISSUE THREAD

**Issue by ruibaby** [lin-liem/weicarus#4]
https://github.com/lin-liem/weicarus/blob/master/layout/widget/profile.ftl#L103

**Comment by zhouh047** [comment]
> https://github.com/lin-liem/weicarus/blob/master/layout/widget/profile.ftl#L103

good job

**Comment by lin-liem** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
